name: autofix.ci
on:
  pull_request:
    paths:
      - "poetry.lock"
      - "pyproject.toml"
      - "src/backend/**"
      - "tests/**"
env:
  POETRY_VERSION: "1.8.2"

jobs:
  lint:
    name: Run Ruff Check and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: install-pinned/ruff@48a5818c5f7ce30e2822b67fb9c26d3e25d31fab
      - run: ruff check --fix-only .
      - run: ruff format .

      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
